toDev <- function(expr, dev, filename, ..., verbose=TRUE) {
  #   Useful function to send a figure (generated by a function) to a plotting
  #   device.  From here:
  #   http://nicercode.github.io/blog/2013-07-09-figure-functions/
  
  #   expr: function to generate a plot
  #   dev: the graphics device
  #   ...: options passed to graphics device
  
  if ( verbose )
    cat(sprintf("Creating %s\n", filename))
  dev(filename, ...)
  on.exit(dev.off())
  eval.parent(substitute(expr))
}